### ISSUE TITLE
6/4/17 TODO

### ISSUE THREAD

**Issue by mitchelloharawild** [mvparrot/face-recognition#3]
- [x] Filter only players now
- [x] Spot checks on ~50 faces randomly sampled (tagged by all), which tags do you most agree with
- [ ] Difference between emotion and 
- [x] Give Di repo access
- [ ] Create new repo on Steff's account (and give both Di and Mitch access)
- [ ] Track a particular, emotive, player... Following them through a sequence of a match.
- [ ] Fix the image tagging box graphic
- [ ] Attach score before image and score afterwards to data set
