### ISSUE TITLE
todo 18/6/17

### ISSUE THREAD

**Issue by dicook** [mvparrot/face-recognition#4]
- [ ] abstract
- [ ] remove contents
- [x] numbering should start with 1. Introduction rather than 0.
- [x] fix image overlays
- [x] section headings need to show purpose, eg. not "regression" but "modeling detection probability"
- [ ] captions need to be expanded, three parts to a caption (1) what's the plot about, (2) what are specific pieces, e.g. colour represents software ... (3) most important thing the reader should learn from the plot
- [x] sort bar charts (fig 7) by overall number of faces matched, rather than alphabetically
- [x] "Discussion" should be "Results overview"
- [x] merge conclusions and future work
- [x] expand references to include the R packages used, and other research articles
- [ ] Journal search; Journal of Quantitative Analysis in Sports?
- [x] coord_flip for Fig 2
- [x] Add mosaic plots of some of the interesting associations
